name: CI

on: [push]

jobs:
  porter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/docker/login@master
      with: 
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    - name: Build 
      run: |
        curl https://deislabs.blob.core.windows.net/porter/latest/install-linux.sh | bash
        PATH=$PATH:~/.porter
        porter build
        porter publish
